# Generated by Django 4.2.11 on 2024-03-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tested_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
