# Generated by Django 4.2.11 on 2024-03-14 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_tested_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tested_at',
        ),
    ]
